global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gitlab-exporter'
    static_configs:
      - targets: ['gitlab-exporter:8080']

  - job_name: 'gitlab-issues-exporter'
    static_configs:
      - targets: ['gitlab-issues-exporter:9200']